### ISSUE TITLE
Trained model.

### ISSUE THREAD

**Issue by vipcualo** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#4]
@mnikitin Thanks you very much for share code.
I don't have a GPU . Do you share trained model file which you trained ?
Thanks you very much.

**Comment by mnikitin** [comment]
@vipcualo hello, thank you for your interest :)
Sure, I can share trained model for face bbox expanding scale of 1.4: https://www.dropbox.com/sh/190o4u3xgof8lpw/AACjNwT1eud5JtN22-qoYTd4a?dl=0
But I think most likely it will be useless for you, because in order to reproduce results you should also use the same face detector as was used during training.
Or retrain model with your desired detector.
