### ISSUE TITLE
Question about the code: crop_images.py 

### ISSUE THREAD

**Issue by prince6show** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#7]

**Comment by prince6show** [comment]
Hello! I want to know what is that in 46 of the code.
            with open('%s/bboxes/%s.txt' % (video_dir, frame_idx), 'r') as bbox_f:

**Comment by prince6show** [comment]
and how many frame of which video you used to achieve the  Results on the home page?
thank you!

**Comment by mnikitin** [comment]
Hello, @prince6show !
This line in code means that I used precomputed face bboxes. I used to work a lot with CASIA-FASD, so in order to speed-up my experiments I ran my face detector on each video frame and save bboxes for each frame in '$VIDEODIR/bboxes/$FRAMEIDX.txt' file.
You can precompute face bboxes using your detector, or fix code in a way that faces would be detected on the fly.

Results on the home page were achieved using all available frames (expect those where face detector failed).

**Comment by prince6show** [comment]
thanks！when i tranined this,
def save_config(cfg):
    save_fname = cfg['experiment_dir'] + "/config.json"
    with open(save_fname, 'w', encoding='utf-8') as f:
        json.dump(cfg, f, sort_keys=True, indent=4)
Object of type 'map' is not JSON serializable.
Do you konw why i? The config is normal in http://www.bejson.com/.

**Comment by prince6show** [comment]
Question about the code: start_train.py

**Comment by mnikitin** [comment]
Hi @prince6show !
The reason of such error is that I wrote the code for Python2, while you're trying to use it with Python3. 
In order everything to be fine in python3, you need to change the line 54 of start_train.py from:
config['data_params']['mean'] = map(float, f.readline().split())
to:
config['data_params']['mean'] = list(map(float, f.readline().split()))

**Comment by prince6show** [comment]
thanks，i just reslove it
